import {
  AlertTriangle,
  ArrowRight,
  Bookmark,
  BookmarkCheck,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  Github,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Menu,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  Save,
  Search,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  type Icon as LucideIcon,
  LogIn,
  LogOut,
} from "lucide-react"
import { Grid } from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Grid,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  settings: Settings,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  command: Command,
  plus: Plus,
  image: Image,
  file: File,
  fileText: FileText,
  creditCard: CreditCard,
  alertTriangle: AlertTriangle,
  check: Check,
  moreVertical: MoreVertical,
  menu: Menu,
  search: Search,
  login: LogIn,
  logout: LogOut,
  bookmark: Bookmark,
  bookmarkCheck: BookmarkCheck,
  save: Save,
}
